CREATE TABLE "users"
(
    "id"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "email"    varchar UNIQUE                                       NOT NULL,
    "password" varchar                                              NOT NULL
);

CREATE TABLE "columns"
(
    "id"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "title"  text                                                 NOT NULL,
    "userId" integer                                              NOT NULL
);

CREATE TABLE "cards"
(
    "id"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "title"    text                                                 NOT NULL,
    "body"     text                                                 NOT NULL,
    "columnId" integer                                              NOT NULL,
    "userId"   integer                                              NOT NULL
);

CREATE TABLE "comments"
(
    "id"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "body"   text                                                 NOT NULL,
    "cardId" integer                                              NOT NULL,
    "userId" integer                                              NOT NULL
);

ALTER TABLE "columns"
    ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "cards"
    ADD FOREIGN KEY ("columnId") REFERENCES "columns" ("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "cards"
    ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "comments"
    ADD FOREIGN KEY ("cardId") REFERENCES "cards" ("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "comments"
    ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");